# Note this file is by far finished, it just includes the reporting part of it as I was adding the reporting app to the Developer Portal
# TODO: Add everything else!

---
apiVersion: backstage.io/v1alpha1
kind: System
metadata:
  name: github-collaborators
  title: GitHub Outside Collaborators
  description: Selection of tools that report on and maintain access to the Ministry of Justice Repositories for Outside Collaborators
spec:
  owner: group:operations-engineering
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: github-collaborators-check
  title: Github Outside Collaborators Check
  description: Pipeline that checks GitHub Outside Collaborators, removes unknown collaborators and raise GitHub repository issues.
  links:
    - url: https://github.com/ministryofjustice/github-collaborators/blob/main/bin/outside-collaborators-check.sh
      title: Pipeline code
spec:
  owner: group:operations-engineering
  type: pipeline
  lifecycle: production
  system: system:github-collaborators
  dependsOn:
    - system:ops-eng-reports
  consumesApis:
    - api:ops-eng-reports-api
