name: Create a Outside Collaborator/s Pull Request
description: >-
  Create an issue from this template will automatically create a valid pull
  request for an outside collaborator/s
title: "Please create an outside collaborator/s pull request"
labels:
  - collaborator
  - pr-create-issue
body:
  - type: textarea
    id: usernames
    attributes:
      label: usernames
      description: Add the GitHub username of each user/s you wish to add, one username per line please
    validations:
      required: true
  - type: textarea
    id: names
    attributes:
      label: names
      description: Add the name of each user/s you wish to add, one name per line please
    validations:
      required: true
  - type: textarea
    id: emails
    attributes:
      label: emails
      description: Add the email address of each user/s you wish to add, one email address per line please
    validations:
      required: true
  - type: input
    id: org
    attributes:
      label: org
      description: Which organisation do the user/s represent?
    validations:
      required: true
  - type: input
    id: reason
    attributes:
      label: reason
      description: The reason why the user/s need access?
    validations:
      required: true
  - type: input
    id: added_by
    attributes:
      label: added_by
      description: >-
        The email address of the MoJ team or person that is requesting GitHub access on behalf of the user? e.g. "ben.ashton@digital.justice.gov.uk"
    validations:
      required: true
  - type: input
    id: review_after
    attributes:
      label: review_after
      description: >-
        When does access for the user/s have to be reviewed? Please use format
        YYYY-MM-DD e.g. 2022-10-10. No longer than 12 months in the future from today.
    validations:
      required: true
  - type: dropdown
    id: permission
    attributes:
      label: permission
      description: What permission does the user/s need?
      options:
        - pull
        - push
        - maintain
        - admin
    validations:
      required: true
  - type: textarea
    id: repositories
    attributes:
      label: repositories
      description: "Add the repositories the user/s need access to, one repository name per line, not the url or full path, just the name of the repository please"
    validations:
      required: true
