module TestConstants
  # Test strings
  TEST_COLLABORATOR_NAME = "some user"
  TEST_COLLABORATOR_LOGIN = "someuser"
  TEST_COLLABORATOR_EMAIL = "someuser@some-email.com"
  TEST_COLLABORATOR_ORG = "some org"
  TEST_COLLABORATOR_REASON = "some reason"
  TEST_COLLABORATOR_ADDED_BY = "other user"
  TEST_COLLABORATOR_PERMISSION = "maintain"
  REPOSITORY_NAME = "somerepo"
  EMPTY_REPOSITORY_NAME = "empty-file"
  TEST_FILE = "terraform/test-repo.tf"
  TEST_USER = "someuser"
  TEST_USER_1 = "someuser1"
  TEST_USER_2 = "someuser2"
  TEST_USER_3 = "someuser3"
  TEST_REPO_NAME = "test-repo"
  TEST_REPO_NAME1 = "test-repo1"
  TEST_REPO_NAME2 = "test-repo2"
  TEST_REPO_NAME3 = "test-repo3"
  TEST_REPO_NAME_EXPIRED_USER = "test-repo-user-expired"
  TEST_DIR = "spec/fixtures"
  TEST_DIR_OVERRIDE = "Constants::TERRAFORM_DIR"
end
