name: Check an organisation user has an approved and verified email domain

# Allows you to run this workflow manually from the Actions tab
on:
  schedule:
    # At the end of every day
    - cron: "0 0 * * *"

jobs:
  approved-email-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-python@v2
        with:
            python-version: '3.10'
            architecture: 'x64'
            cache: 'pip'
      - run: |
          python3 -m pip install --upgrade pip
          python3 -m venv venv
          source venv/bin/activate
          python3 -m pip install websockets aiohttp==3.8.1 gql==3.0.0rc1 ghapi
      - run: python3 scripts/approved-email-domain-check.py ${{ secrets.ADMIN_GITHUB_TOKEN }} > output.txt
#       - uses: actions/upload-artifact@v2
#         with:
#           name: output_report
#           path: scripts/output.txt
