name: Check an organisation user has an approved and verified email domain

# Allows you to run this workflow manually from the Actions tab
on:
# Feature is currently disabled as some GH MoJ users do not have an MoJ email address.
#   schedule:
#     # At the end of every day
#     - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  approved-email-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          architecture: 'x64'
          cache: 'pip'
      - run: |
          python3 -m pip install -r scripts/requirements.txt
          python3 scripts/approved-email-domain-check.py ${{ secrets.ADMIN_GITHUB_TOKEN }} > output.txt
      - uses: actions/upload-artifact@v3
        with:
          path: output.txt
