name: Check Fork Status
on:
  pull_request_target:
    types: [opened, edited, reopened, synchronize]

jobs:
  check-fork:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - name: Check if pull request in a fork
      - run: |
          python3 -m pip install -r scripts/requirements.txt
          python3 scripts/check-fork-status.py ${{ toJson(github.event.pull_request) }} ${{ secrets.ADMIN_GITHUB_TOKEN }}
