name: Check Fork Status
on:
  pull_request_target:
    types: [opened, edited, reopened, synchronize]

jobs:
  check-fork:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - run: python3 -m pip install -r scripts/requirements.txt
      - run: python3 scripts/check-fork-status.py
        env:
          PR_DATA: ${{ toJson(github.event.pull_request) }}
          TOKEN: ${{ secrets.OPS_BOT_TOKEN }}
