name: Compare collaborators in Terraform against GitHub

on:
  # Sunday 3pm
  schedule:
    - cron: "0 15 * * 0"
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - run: scripts/compare-terraform-to-github.py ${{ secrets.ADMIN_GITHUB_TOKEN }}
