name: Check correct permission tags are used in Terraform files
on:
  workflow_dispatch:
  pull_request:
    branches:
      - main
    paths: "terraform/**"
  issues:
    types: [opened]

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: scripts/permission-check.sh
