name: Ensure PRs are using the correct permission tags from Terraform
on:
  workflow_dispatch:
  pull_request:
    branches:
      - main
    paths: 'terraform/**'

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: scripts/permission-check.sh