name: Create and send the outside collaborators JSON data and remove manually added collaborators

on:
  workflow_dispatch:
  schedule:
    - cron: "23 2 * * *"

env:
  OPERATIONS_ENGINEERING_REPORTS_HOST: ${{ secrets.OPERATIONS_ENGINEERING_REPORTS_HOST }}
  OPS_ENG_REPORTS_URL: ${{ secrets.OPERATIONS_ENGINEERING_REPORTS_HOST }}/github_collaborators
  RUBY_VERSION: 3.0.3

jobs:
  post-data-to-opseng-reports:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ env.RUBY_VERSION }}
          bundler-cache: true
      - run: bin/post-data.sh
        env:
          ADMIN_GITHUB_TOKEN: ${{ secrets.ADMIN_GITHUB_TOKEN }}
          OPERATIONS_ENGINEERING_REPORTS_API_KEY: ${{ secrets.OPERATIONS_ENGINEERING_REPORTS_API_KEY }}
      - name: Remove manually-added collaborators
      - run: bin/remove-undefined-collaborators.rb
        env:
          ADMIN_GITHUB_TOKEN: ${{ secrets.ADMIN_GITHUB_TOKEN }}
          OWNER: "ministryofjustice"
      - name: Remove collaborators attached to locked repositories
        uses: actions/setup-python@v2
        with:
            python-version: '3.10'
            architecture: 'x64'
            cache: 'pip'
      - run: python3 -m pip install -r scripts/requirements.txt
      - run: python3 scripts/remove-collaborator-locked-repos.py ${{ secrets.ADMIN_GITHUB_TOKEN }} > output.txt
      - uses: actions/upload-artifact@v2
        with:
          path: output.txt
      - name: Report failure to Slack
        if: always()
        uses: ravsamhq/notify-slack-action@v1
        with:
          status: ${{ job.status }}
          notify_when: 'failure'
          notification_title: 'Failed GitHub Action Run'
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}

