name: Remove a collaborator from a repository
on:
  workflow_dispatch:
    inputs:
      repository:
        description: Repository name, e.g. "myrepo"
        required: true
      github_user:
        description: GitHub username of the collaborator
        required: true

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          path: main
      - uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - run: python3 -m pip install -r scripts/requirements.txt
      - run: python3 scripts/remove-collaborator.py ${{ secrets.OPS_BOT_TOKEN }} ${{ github.event.inputs.repository }} ${{ github.event.inputs.github_user }}
