name: Report collaborators defined in Terraform who are not present in GitHub

on:
  schedule:
    # Sunday 3pm
    - cron: "0 15 * * 0"
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    inputs:
      tags:
        description: 'Placeholder'
        required: false

env:
  RUBY_VERSION: 3.1.0

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ env.RUBY_VERSION }}
          bundler-cache: true
      - run: bin/compare-terraform-to-github.rb
        env:
          ADMIN_GITHUB_TOKEN: ${{ secrets.ADMIN_GITHUB_TOKEN }}
          REPO: ${{ github.event.inputs.repository }}
          USERNAME: ${{ github.event.inputs.github_user }}
