name: Repository check
on:
  workflow_dispatch:

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          path: main
      - run: bash scripts/repository-check.sh ${{ github.event.inputs.github_user }} ${{ secrets.MOJ_COLLABORATORS_GENERAL_ADMIN_BOT_PAT }}
