# This is a basic workflow to help you get started with Actions

name: Used to test adhoc workflows - runs on branch workflow_test

# Controls when the workflow will run
on:
  # Triggers the workflow on push events but only for the workflow branch
  push:
    branches:
      - workflow_test

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    inputs:
      tags:
        description: 'Test scenario tags'
        required: false

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
        with:
          ref: workflow_test

      # IMPORTANT
      # Change here to test different Ruby scripts
      - run: bin/workflow-test.rb
        env:
          ADMIN_GITHUB_TOKEN: ${{ secrets.ADMIN_GITHUB_TOKEN }}
          REPO: ${{ github.event.inputs.repository }}
          USERNAME: ${{ github.event.inputs.github_user }}
